language: c
before_install:
  - sh ./tests/travis-ci/install-travis-prereqs.sh
before_script:
  - make CONFIG_CLOCK_GETTIME=n CONFIG_MPI=y CONFIG_ZLIB=y CC=mpicc
script:
  - make CONFIG_CLOCK_GETTIME=n CONFIG_MPI=y CONFIG_ZLIB=y CC=mpicc test
